sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - LIBRARY_PATH="/tmp/usr/lib;$LIBRARY_PATH"
before_install:
  - wget https://matrix.org/git/olm/snapshot/olm-2.2.2.tar.bz2
  - tar -xvf olm-2.2.2.tar.bz2
  - pushd olm-2.2.2 && make && make PREFIX="/tmp/usr" install && popd
  - rm -r olm-2.2.2
install: pip install tox-travis
script: tox
